#!/bin/sh
mkdir /sys /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t proc proc /proc

#setting shared memory region config
mkdir -p /dev/shm
mount -t tmpfs -o mode=1777,size=1G tmpfs /dev/shm

ip link set dev eth0 up 
#exec /bin/sh
exec /main eth0 ping
